### ISSUE TITLE
Returning primary key on insert procedure

### ISSUE THREAD

**Issue by imclassy** [osalvador/tapiGen2#5]
Hello, I'm currently using tapigen2, and it would be useful to add an "ins" procedure with an OUT parameter returning the primary key of the inserted record to avoid manual procedures and code that do things like this:

DECLARE
    v_key table.pkey%type;
BEGIN
    INSERT INTO table (value1, value2) 
         VALUES ('foo', 'bar')
         RETURNING pkey INTO v_key;
END;

This is done when triggers or autogenerated identity columns are used.

Keep the great work!

**Comment by osalvador** [comment]
Hi @imclassy 

It is a great improvement, the procedure `ins` includes the `in out` parameter, it could be included in this parameter.
