### ISSUE TITLE
When generating tapi for long table name

### ISSUE THREAD

**Issue by cryptopascal** [osalvador/tapiGen2#6]
I think  there is an issue when trying to generate a TAPI, for table that has a long name.
For example, exec tapi_gen2.create_tapi_package (p_table_name => 'AR_SUIVI_CONSULTATION_CMD')
failed. Package's variables exceeded 30 cara;

**Comment by osalvador** [comment]
The names of the objects in the oracle databases are 30 Bytes, plus tapigen2 adds 5 more characters to the table name to put the prefix 'TAPI_'

I could add a new parameter with the package name of the TAPI, or trim the table name if it exceeds 25 characters.

**Comment by cryptopascal** [comment]
Also for variable such **p_**ar_suivi_consultation_cmd**_rec** , so here tapigen2 added 6 characters.
